name: Benchmarks

on:
  pull_request:
    paths: ['src/**', 'tests/**']
  push:
    branches: [main]

concurrency:
  group: bench-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bench:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # make sure origin/main is available for diff
      - run: git fetch origin main --depth=1

      - uses: pnpm/action-setup@v4
        with: { version: 10.13.1 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      # install Playwright browsers for the browser benches
      - run: pnpm exec playwright install --with-deps

      # run benches for node + browser and compare with baseline
      - run: pnpm bench:compare

      # on pushes to main, update badge and baseline
      - if: github.ref == 'refs/heads/main'
        run: |
          node scripts/update-badge.js
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add bench/bench-*.json
          git commit -m "chore(bench): update benchmark baseline & badge [skip ci]" || echo "no changes"
          git push
