name: Release

on:
  # Only run when you push a semver tag like v1.2.3
  push:
    tags:
      - 'v*.*.*'
  # Also allow manual triggering from the Action UI
  workflow_dispatch:

jobs:
  release:
    if: ${{ secrets.NPM_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm build

      - name: Create GitHub Release and Publish to npm
        uses: changesets/action@v1
        with:
          # this runs `pnpm publish --no-git-checks --access public`
          publish: pnpm publish --no-git-checks --access public
          commit: 'chore(release): publish'
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
